### ISSUE TITLE
Top Edited Wiki Pages should omit User: pages

### ISSUE THREAD

**Issue by tantek** [indieweb/this-week#20]
As illustrated by the [2020-10-02 draft newsletter](https://indieweb.org/this-week/2020-10-02.html#changed-wiki-pages), the Top Edited Wiki Pages includes User: pages which are more personal projects or bot updates and don't really add significant information to the This Week newsletter. User: pages should be omitted from the Top Edited Wiki Pages section.

(Originally published at: https://tantek.com/2020/275/b1/)

**Comment by capjamesg** [comment]
I agree that the User pages do not provide significant context. I see the Top Edited Wiki Pages section as a place to find out about what the community has been talking about in the last week (in large part due to the correlation between discussions in chat and updates on the wiki) as opposed to a place to find out about personal contributions.
